FROM python:3.8-slim
RUN apt-get update && apt-get install -y openssh-client vim
COPY MachineInterface/requirements.txt /app/MachineInterface/requirements.txt
RUN pip install -r /app/MachineInterface/requirements.txt
COPY . /app
WORKDIR /app/MachineInterface
RUN cat /app/MachineInterface/misc/ssh_hpda_config >> /etc/ssh/ssh_config
RUN mkdir -p /root/.ssh/controlmasters
CMD python interface.py
