FROM python:3.8-slim
RUN apt-get update && apt-get install -y openssh-client vim
COPY MachineInterface/requirements.txt /app/MachineInterface/requirements.txt
RUN pip install -r /app/MachineInterface/requirements.txt
COPY . /app
WORKDIR /app/MachineInterface
CMD python interface.py --config machines.yaml
